### ISSUE TITLE
Private WPT instance on GCP - multi zones or single zone?

### ISSUE THREAD

**Issue by jonchenn** [WPO-Foundation/webpagetest-docs#12]
Hi WPT experts, I'm creating private WPT instances on GCP based on this guide: https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/gce_agents.md#auto-scaling

One thing that I'm not sure is setting either multi-zone or a single-zone, as described here: https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/gce_agents.md#auto-scaling

Multi-zone usually makes sense for high availability in a region. However, for auditing consistency, single-zone seems a better choice when setting up GCP instance group. I wonder what's the rationale behind this suggested setting?

**Comment by pmeenan** [comment]
Sorry, doesn't particularly matter and I've done both.  If you're using preemptable instances it's just more likely to get capacity if you don't fix it to a single zone.
