### ISSUE TITLE
'=' sign with in setCookie value cannot be skipped

### ISSUE THREAD

**Issue by rguuduru** [WPO-Foundation/webpagetest-docs#19]
Unable to escape = sign in cookide value. Wondering if we cover this in documentation.

setCookie http://www.test.com cookiekey=**cookievalueprefix=cookievaluesuffix**

**Comment by pmeenan** [comment]
You don't need to escape it, it should just work.

```
setCookie	https://www.webpagetest.org	testcookie=tomato=veg
navigate	https://www.webpagetest.org
```

![Screen Shot 2021-01-17 at 2 48 05 PM](https://user-images.githubusercontent.com/444165/104854150-15adfd80-58d3-11eb-88b8-8bc75a9dc29a.png)
