### ISSUE TITLE
Scripting documentation mentions Desktop Version and loading a script from File

### ISSUE THREAD

**Issue by asos-giovannip** [WPO-Foundation/webpagetest-docs#20]
Hi, 

Looking into the scripting documentation I've noticed that it mentions:

`You can test a script in the desktop version by selecting "Run Script" from the File menu.`

I'm not entirely sure what this is referring to. Should it be removed?

**Comment by pmeenan** [comment]
Should be fixed now, thanks.  Those were a few lingering references from the original IE plugin which was a desktop app.
