### ISSUE TITLE
Doc links broken with latest commit?

### ISSUE THREAD

**Issue by raphaelb** [WPO-Foundation/webpagetest-docs#22]
Just a heads up - lots of external sites link to e.g.:
https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Scripting.md#blockdomains

Which should go instead to:
https://github.com/WPO-Foundation/webpagetest-docs/blob/main/src/scripting.md

Even the links on this page are incorrect: https://github.com/WPO-Foundation/webpagetest-docs

**Comment by tkadlec** [comment]
Yeah..I need to update that readme.md for sure!

The docs are getting some needed love—a facelift, many sections getting rewritten/added, etc. The canonical source going forward for that link is https://docs.webpagetest.org/scripting/.

(The source will still be this repo though to make it easy to file issues/contribute, etc)

Will update the README.md ASAP.

**Comment by tkadlec** [comment]
README.md is in much better shape.
