### ISSUE TITLE
The test script execution queue is sometimes stuck

### ISSUE THREAD

**Issue by zhidongzhang** [WPO-Foundation/webpagetest-docs#54]
Hi,
The test script execution queue is sometimes stuck.Every time I need to restart the service.How to check what happened?

Thanks

**Comment by Siddhantshukla814** [comment]
Hi zhidongzhang, Could you please share your script so we can take a look at it to better understand the issue

**Comment by zhidongzhang** [comment]
> Hi zhidongzhang, Could you please share your script so we can take a look at it to better understand the issue
Thanks，I replaced the agent-21.07,it's worked
