### ISSUE TITLE
Document new `setExecutionContext` command

### ISSUE THREAD

**Issue by rik** [WPO-Foundation/webpagetest-docs#77]
Implemented in https://github.com/WPO-Foundation/wptagent/pull/584

**Comment by tkadlec** [comment]
Done? :) https://docs.webpagetest.org/scripting/#setexecutioncontext

**Comment by rik** [comment]
Thanks! (Looks like I opened the issue as you were pushing the commit)

**Comment by tkadlec** [comment]
:) Good timing!
