### ISSUE TITLE
Webpage Test Agent Middle East Bahrain AWS EC2

### ISSUE THREAD

**Issue by haseebsaif** [WPO-Foundation/webpagetest-docs#9]
I am getting this error while I am trying to run a test for Middle East (Bahrain) Region.

 **EC2:Launching EC2 instance. Region: me-south-1, AMI: ami-099c65b608dce0ba3, error: The requested configuration is currently not supported. Please check the documentation for supported configurations.**

I have setup EC2 Webpage Test Server and its running test for all the other regions perfectly and creating Webpage Test Agents as per Region but when I try to run a test in Bahrain region. I am getting the above-specified region.

is it a known issue? Please guide.

I appreciate your help.

**Comment by pmeenan** [comment]
Go to your EC2 console and see if you can manually launch instances there (of any image) and what instance sizes are available.  My guess is it is one of 2 things:

1 - The region needs to be "activated" for the account
2 - The default c4.large (or whatever the current default is) instance size isn't a configuration supported there and you need to specify a different instance size (c5.large) in locations.ini

**Comment by haseebsaif** [comment]
Thank you very much.

The issue was c4.large, In Middle East(Bahrain) AWS don't have c4.larage. I just changed it to c5 and it worked.

Cheers
